### ISSUE TITLE
Columns (todo's)

### ISSUE THREAD

**Issue by SeverS** [AkashaProject/Community#221]
- [x] fix my entries (entry card styling)
- [x] fix a bug where fetching is done multiple times
- [x] add column placeholders for empty column
- [x] profile page columns reset on navigation
- [x] new column tag and user preview section
- [x] fix column new entry dot not showing
- [x] check profileFollowers and profileFollowings iterators (updates needed)
- [x] cleanup and merge
